"""
routers/alerts.py
────────────────────
/api/alerts — the Alerts page: sortable, risk-scored, explainable list of
flagged works. Every reason string here was generated by ml/explain.py
FROM the trained models' outputs at training time and stored verbatim in
the work_risk_scores table — this endpoint does not compute anything,
just serves it filtered/scoped/paginated.
"""

import math
import sys
import os

from fastapi import APIRouter, Depends, Query

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from auth import get_current_user, CurrentUser
from db_utils import enforce_scope, query_works, clean_nan

router = APIRouter(prefix="/api/alerts", tags=["alerts"])


@router.get("")
def list_alerts(
    page: int = Query(1, ge=1),
    page_size: int = Query(25, ge=1, le=200),
    risk_band: str = Query("High", description="High | Medium | Low | All"),
    state: str | None = None,
    ida: str | None = None,
    mp_name: str | None = None,
    min_risk_score: float | None = None,
    user: CurrentUser = Depends(get_current_user),
):
    filters = {"state": state, "ida": ida, "mp_name": mp_name, "min_risk_score": min_risk_score}
    if risk_band and risk_band.lower() != "all":
        filters["risk_band"] = risk_band.capitalize()
    filters = enforce_scope(filters, user)

    df, total = query_works(filters, page=page, page_size=page_size, sort_by="risk_score", sort_dir="desc")

    alerts = []
    for _, row in df.iterrows():
        alerts.append({
            "work_id": row["work_id"],
            "state": row["state"],
            "district_agency": row["ida"],
            "mp_name": row["mp_name"],
            "constituency": row["constituency"],
            "work_category": row["work_category"],
            "work_description": row["work_description"],
            "sanction_amount": row["sanction_amount"],
            "risk_score": row["risk_score"],
            "risk_band": row["risk_band"],
            "badges": {
                "anomaly_score": row["anomaly_score"],
                "delay_risk_pct": row["delay_risk_pct"],
                "cost_risk_pct": row["cost_risk_pct"],
                "duplicate_score": row["duplicate_score"],
            },
            "reasons": row["risk_reasons"].split("; "),
        })

    return clean_nan({
        "page": page,
        "page_size": page_size,
        "total": int(total),
        "total_pages": math.ceil(total / page_size) if page_size else 0,
        "alerts": alerts,
    })
